### ISSUE TITLE
Cannot open google calendar with pimatic

### ISSUE THREAD

**Issue by ccvh** [thost96/pimatic-google-calendar#1]
Hey!

Followed your guide to install, but when i try to open
"http://192.168.178.100:8080/google/calendar" (in my case, that's the correct pimatic url), i just get a blank window saying "Cannot GET /google/calendar".

What am i doing wrong?

Thanks a lot!

**Comment by thost96** [comment]
Please restart pimatic before trying to open this url.

**Comment by ccvh** [comment]
Meh, i'm a bit tired. Thanks a lot, worked ;-)

**Comment by thost96** [comment]
No problem, nice to hear ;-)
