### ISSUE TITLE
google-calendar-today device not showing any entries

### ISSUE THREAD

**Issue by ccvh** [thost96/pimatic-google-calendar#2]
Sorry to disturb you again. 
I set up pimatic-google-calendar yesterday and added the device for showing the current day now.
But it's not showing anything beside the date and the (empty) timeline (there are several entries in my google calendar). 
Which calendar (there are more than 1 on my account) does this plugin chose? Any need to chose manually? 

Edit: I've restarted pimatic, as well as the pi to see if it's updating, nothing happened.

Thanks in advance, 
Greetings, Chris

**Comment by thost96** [comment]
I encounter some socket hang up errors on my second pimatic install. Will have a look at this soon. 

At the moment only the primary calendar is shown. More calendars will be supported in the future, see the [todo ](https://github.com/thost96/pimatic-google-calendar#todo) section.

**Comment by thost96** [comment]
This should be fixed with version 0.3.5 of pimatic-google-calendar. Please update the plugin.
