### ISSUE TITLE
The OAuth client was not found

### ISSUE THREAD

**Issue by mpuff** [thost96/pimatic-google-calendar#3]
if i will connect to ttp://pimatic-ip/google/calendar i get the error 401
Error: invalid_client

The OAuth client was not found.

access_type=offline
scope=https://www.googleapis.com/auth/calendar.readonly
response_type=code

the OAuth-2.0-Client-ID is created.
what am I doing wrong?

Thank you for your help :)

**Comment by thost96** [comment]
could you try the latest version of the plugin again? 

please also check, that you copied the whole client_id (including the apps.googleusercontent.com).

**Comment by thost96** [comment]
no response for one month. Closing this for now!
