### ISSUE TITLE
doesn't show any calendar

### ISSUE THREAD

**Issue by cm86** [thost96/pimatic-google-calendar#4]
Hello,
i followed the instructions to get this nice plugin to work.
But it doesn't show any entry in my calendar...
...
after i followed the URL: http(s)://pimatic-ip/google/calendar
...
i get a key this i puted at the end of this:
...
http(s)://pimatic-ip/google/calendar?auth=code here
...
but then i get again the question to let the plugin access the api followed by a nother key
...

mfg
Chris

**Comment by thost96** [comment]
did you restarted pimatic after the setup as described in step 12? try another restart after you copied the code from the google page to your pimatic install.

EDIT: 

i noticed a litte mistake in the readme file. Try to open the following url:

http(s)://pimatic-ip/google/calendar?code=code here

**Comment by thost96** [comment]
should be fixed with [version v0.2.7](https://github.com/thost96/pimatic-google-calendar/commit/94a5a7692b8faf08e3877c5f6267853b3c2fdc62)
